# Generated by Django 2.2.2 on 2019-06-06 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntermediateResult',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intermediate_results', models.ManyToManyField(blank=True, to='api.IntermediateResult')),
            ],
        ),
        migrations.CreateModel(
            name='LeafResult',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, related_name='leaf_images', to='api.ImageUrl')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seed_url', models.CharField(max_length=100)),
                ('depth', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing')], default='PROCESSING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Result')),
            ],
        ),
        migrations.AddField(
            model_name='intermediateresult',
            name='leaf_results',
            field=models.ManyToManyField(blank=True, related_name='leaf_results', to='api.LeafResult'),
        ),
        migrations.AddField(
            model_name='intermediateresult',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='intermediate_links', to='api.Page'),
        ),
        migrations.AddField(
            model_name='intermediateresult',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_page', to='api.Page'),
        ),
        migrations.AddField(
            model_name='intermediateresult',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_parent', to='api.Page'),
        ),
    ]
