# Generated by Django 2.2.2 on 2019-06-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediateresult',
            name='links',
        ),
        migrations.AddField(
            model_name='intermediateresult',
            name='intermediate_results',
            field=models.ManyToManyField(blank=True, related_name='_intermediateresult_intermediate_results_+', to='api.IntermediateResult'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
